language: node_js

matrix:
  include:
    - node_js: stable
      os: osx
      script: npm run test:integration 
    - node_js: stable
      os: linux
      dist: trusty
      script: npm run test:unit
      sudo: required
