language: node_js
matrix:
  include:
  - node_js: '9'
    os: osx
    addons:
      chrome: stable
      firefox: latest
    script: npm run test
  - node_js: '9'
    sudo: required
    os: linux
    dist: trusty
    addons:
      chrome: stable
      firefox: latest
    before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    script:
    - npm run test:unit
    - if [ "TRAVIS_PULL_REQUEST" = "false" ]; then npm run test:sauce; fi
env:
  global:
  - secure: ZU6BvW870p+0HciUew8y5CmyJTp5lsxHNelJonyL8J/zdBAFcB2rvdSNQojr5vMVE+WAzNcEw2U6uKv+zvSpamSFJkY6TWopx5z19A8CivrJMk9w5j6cY9997on/sVjDkyrgi3iAAK1oQh1slvX8gRM+hlYJXcxeZ6hx44DKm/6hC+M/l4k/W2q/KQAjsF+SOGqeVo2GKuPXhETZwrf8UFDQ0pY2KZ2UBxxqGMBAqLhi/FGetOvpG3pmkKDi4b7drUojqf0kArFKaq4gcrIsswnMscRLFKZSxcFVsJ5fGIa1Qo4TYX3bYaagCY8bItct6+d5SE7gpeRRAc3EcjFqM+cR5oFsoRqsDT6jQsQhtAF5oUtldVPBmjuZ7TtAZlAu3ImJ2cKWTvTwCFxY7TtGy1m3OSj85MTIF1A1XH06chd2YGfa8vYABkR6sfHQmWHxaw+eGiWjzQ5NPtlEmMhC70OlOyX26JN3SkBdXjbkG8pi54qaUJwsOBSaW+lSJF5trWSrnb9JgOklCMJjWRb8rtlS0fpOOAti2ZPDDbptnFb/DxtJDWLnzD2uedQGn/VdpnZ0LMQb3JqLMyyAI+qVJ/DK522D10iFigj5P9G1UUPOTKm+poGbRp3ZQayNC6/27jjBT+9VG4HNsCt3XQRItZpJ6mpSEdKggLpMd/QcnWU=
  - secure: R7qkZz+O2sQslTXA8M7SPzKfsNkGAai+KNFKwvedWuZR3PcXDWv0XrBFVqhHGxdGubf8A8ABAlYT4V9HUx3v0wTjdym4EEPaMs5EbgktC6NTiIT4ZuEPXjXjVDSSRV5+DExKNo+t9/T9ohwNlJdmGdRUSd0qVIUJB/zpDd+HIPt8X7DPXLdn8vdq/Ays2UPfH3880Q8UbHkmmm7gZVmFAQa0ay6XRS7y30KTLSIeve/bZgsLRN8zB3uWqrxub4Kj7CIsu8eYbfVIjh5DosRzLXipIJaQ1tCslRBC+y8QwX0g9r4sGnruxTqiIECji2nfAx9ha0l21kmHW8olvQy7x+G+w25QrLZOWdC5SbBgCylczSNKtPYkwdFbuapuISmGLt2TvmnbVwe7MfYO0JSQQIgK6IEOX4VyxAJuL/JH6bWLjk47NDEG8UC+gIOlJk4WhCa/FMcXoKo+bTSZl5XGCyuNov+tnrtK2kYyLhkU8XsHNEYiE+ZBYDrnR7jsnvMTQDB/mTMcfDpCQxNteUF786Eo/LlsxBbyG7nHqLaAF9a2cGUNqFxIWo/MyotXqKgaMZzFUbxAdchBval3+MV2VYQU6SlzZnYYnS+t4mT5ulXx+JjovY8mxpZV9oeGhJCvmyGeZfZmQSSngdDDgBxUGy53Q6MumXIDHKfwQidWVGs=
