language: node_js
matrix:
  include:
  - node_js: '9'
    os: osx
    addons:
      chrome: stable
      firefox: latest
    script: npm run test
  - node_js: '9'
    sudo: required
    os: linux
    dist: trusty
    addons:
      chrome: stable
      firefox: latest
    before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    script:
    - npm run test:unit
    - npm run test:sauce
env:
  global:
  - secure: RUpnTHmYNEKIb9zrcrY+Pl8nyViWHh6E7LVroJwKp5CVqh6QxayA/FvjF/4Pc11xegMiuaCDi8woT5ljuDsY+1RAbCYNxSyc1UExnbggK7223Q1LXuwfZkHx9PakYhnzTlZ3NB1JJOcH1Ob18iiILqefU7Gdy0WNJlLc8rwZ/T5bnzUlYrc2wYtwPYCDls1W1gIGg3w2ur3cK34McOo4cQ7ggXuibzhsG7r/PryL/nvwkkshWTMkb8OagioDs3CIhqFFtRiuOe6GdsWyxcMDrATb0/70B/4WGCyfdqYpnM9XWEJnNGU14ULx2bBVyyd9wVx2yCUAwKI2+InNBJbckcROuoo3TBl3fYyISAwGAHEkRXgDfLYMVPEALb6C5F3qZHZJ9Ryf7bVid6bZ91aQPtTog7wtbRfnPYyX7kiDqrXndOmdkWHVnkZc4IfVCG3RxerQg/YLDyfWHdD2iPzA22i6PwKKXdCPUwSYeyWuntw9DgPL/9CT+MX8BrTS4Nva17Krjpbm/QdcP3+fskHIwi7+qNGROR5k5tQG/2zlHuhe8ACJg0jQUlezBcBxN/pUrcYdLAj3jJsh3MeOBWKHnrq5cmVRdiiL0CW8+O/3D7xN7ryxtEquQEH4eRxEiRYDtwjLyo0O6Oeh5KoWqZDwGMhLck35wI6vMZgGhkkHY8M=
  - secure: Fj62vKxtgbsC771OIilRKrhDzHvdJt+PjoIUYKT5tDSYG7lDizw2cXPfrGU1CJNlRyPC01mlUGftv3w9xP9nawAj5SgWhOFXI7l2CHd/P5UIsHVq5nDhPbSSMu9BK4YQJH+F/nwR6bDQXPqZxeQ5sGDGgIdry1ig/R8nb5Y71Vw6QmT6uc6Nwpf79RbqxPrb6rpGylNLTQHur0HEMYYNKEOrd8D265OMy5Cc/dB6q//nI9IY04Iu43XYX1qoadJR++Q1tc/WQMnyLIbwJC7SOwBKJ505Za/SK5kcP2r73lDOEBGsyTVaff+VXsWxVkwCwUIrV0bnxbuSavQBHzDWU5Kox5jFDb010XcntarEtx7jGXRTCsBVkAGAhGuHgwwxo2iV4u8KCL2bwLDnBb+eO3H39GZN2tqMYD18xKcSBdTETEs5QKLnOUzbn5xABITsaATlqgyFIhjL9lBrU3RO/55EsS3QEgICpIKAAqQCCHqd2im8cQ17o9TMZPVbNy8WpcgokYhvTA9qWdZ3/iU5u0JGYCbKra+KGr1Y0SmOUy2qBYR7H0tm8eCPLh0iUAyKNlrbXgRz/KnaVIFVd7GZllWBCJQainUeJuvgi98SGLE9XjxCKaVf6ACJeQ9JoFEZbdhPDnH+To53Sch8RcrYDCBdJOzK7DIsM7nhm7OLSZE=
